import { useEffect, useState } from "react";
import { PageHeader } from "@/components/common/page-header";
import { Button } from "@/components/ui/button";
import { ImuViewer } from "@/components/viewer/imu-viewer";
import { useDevice } from "@/context/device-context";
import type { TelemetrySample } from "@/types/device";

type View = "perspective" | "front" | "top" | "side";
export function AttitudePage() {
  const { latest, stats } = useDevice(); const [view, setView] = useState<View>("perspective"); const [reference, setReference] = useState<TelemetrySample["quaternion"]>();
  useEffect(() => { if (latest && !reference) setReference(latest.quaternion); }, [latest, reference]);
  return <div className="flex min-h-full flex-col"><PageHeader title="??" description="????????????????????????????????????" actions={<div className="flex gap-1">{([['perspective','??'],['front','??'],['top','??'],['side','??']] as const).map(([v,l]) => <Button key={v} size="sm" variant={view===v?'secondary':'ghost'} onClick={() => setView(v)}>{l}</Button>)}<Button size="sm" variant="secondary" onClick={() => latest && setReference(latest.quaternion)}>??????</Button></div>} /><div className="grid min-h-[650px] flex-1 grid-cols-[minmax(0,1fr)_330px] gap-4 p-5"><section className="overflow-hidden rounded-lg border border-border bg-[#0f1317]"><ImuViewer sample={latest} reference={reference} view={view} /></section><aside className="rounded-lg border border-border bg-surface-1"><div className="border-b border-border px-4 py-3 text-xs font-medium">????</div><div className="grid grid-cols-3 border-b border-border py-4 text-center">{[['??',latest?.roll],['??',latest?.pitch],['??',latest?.yaw]].map(([label,value]) => <div key={String(label)} className="border-r border-border last:border-0"><div className="text-[10px] tracking-wider text-muted-foreground">{label}</div><div className="mt-1 font-mono text-base tabular-nums">{typeof value==='number'?`${value.toFixed(2)}?`:'?'}</div></div>)}</div><div className="p-4"><div className="text-[10px] tracking-wider text-muted-foreground">??? ? w x y z</div><div className="mt-2 grid grid-cols-2 gap-x-4 gap-y-2 font-mono text-xs tabular-nums">{(latest?.quaternion??[0,0,0,0]).map((value,index)=><div key={index} className="flex justify-between"><span className="text-muted-foreground">{['w','x','y','z'][index]}</span><span>{latest?value.toFixed(6):'?'}</span></div>)}</div></div><div className="border-t border-border p-4 text-xs"><div className="flex justify-between py-1"><span className="text-muted-foreground">????</span><span className="font-mono">{stats.fusionHz.toFixed(0)} Hz</span></div><div className="flex justify-between py-1"><span className="text-muted-foreground">????</span><span className="font-mono">{stats.hostOutputHz.toFixed(0)} Hz</span></div><div className="flex justify-between py-1"><span className="text-muted-foreground">VQF ??</span><span className="font-mono">{latest?`${latest.vqfUs.toFixed(1)} ?s`:'?'}</span></div></div></aside></div></div>;
}
