[package]
name = "at32-motion-studio"
version = "0.1.0"
description = "Professional motion and embedded device studio for AT32F423 + LSM6DSV"
authors = ["Mathonix"]
edition = "2021"

[lib]
name = "at32_motion_studio_lib"
crate-type = ["rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
parking_lot = "0.12"
serialport = { version = "4.7", default-features = false }

[profile.release]
lto = true
codegen-units = 1
strip = true

